Models/Tinh.cs
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace NguyenThanhQuan_QLThongTin_MVC.Models
{
    public class Tinh
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Trường Tỉnh không được để trống")]
        [Display(Name = "Tên Tỉnh")]
        public string TenTinh { get; set; }
        public ICollection<Huyen> Huyens { get; set; }
    }
}

Controllers/HuyenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NguyenThanhQuan_QLThongTin_MVC.Data;
using NguyenThanhQuan_QLThongTin_MVC.Models;

namespace NguyenThanhQuan_QLThongTin_MVC.Controllers
{
    public class HuyenController : Controller
    {
        private readonly QLThongTinDbContext _context;

        public HuyenController(QLThongTinDbContext context)
        {
            _context = context;
        }

        // GET: Huyen
        public async Task<IActionResult> Index(string? key = "")
        {
            if (key == null || key == "")
            {
                var qLThongTinDbContext = _context.Huyens.Include(h => h.Tinh);
                return View(await qLThongTinDbContext.ToListAsync());
            } else
            {
                IEnumerable < Huyen > lstHuyen= _context.Huyens.Where(h => h.TenHuyen.Contains(key));
                return View(lstHuyen);

                //var qLThongTinDbContext = _context.Huyens.Include(h => h.Tinh);

                //List<Huyen> newList = new List<Huyen>();

                //foreach(Huyen huyen in qLThongTinDbContext)
                //{
                //    if (huyen.IdTinh == id)
                //    {
                //        newList.Add(huyen);
                //    }
                //}
                //return View(newList);
            }
        }

        // GET: Huyen/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Huyens == null)
            {
                return NotFound();
            }

            var huyen = await _context.Huyens
                .Include(h => h.Tinh)
                .FirstOrDefaultAsync(m => m.IdHuyen == id);
            if (huyen == null)
            {
                return NotFound();
            }

            return View(huyen);
        }

        // GET: Huyen/Create
        public IActionResult Create()
        {
            ViewData["IdTinh"] = new SelectList(_context.Tinhs, "Id", "TenTinh");
            return View();
        }

        // POST: Huyen/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdHuyen,TenHuyen,IdTinh")] Huyen huyen)
        {
            if (ModelState.IsValid)
            {
                _context.Add(huyen);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdTinh"] = new SelectList(_context.Tinhs, "Id", "TenTinh", huyen.IdTinh);
            return View(huyen);
        }

        // GET: Huyen/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Huyens == null)
            {
                return NotFound();
            }

            var huyen = await _context.Huyens.FindAsync(id);
            if (huyen == null)
            {
                return NotFound();
            }
            ViewData["IdTinh"] = new SelectList(_context.Tinhs, "Id", "TenTinh", huyen.IdTinh);
            return View(huyen);
        }

        // POST: Huyen/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdHuyen,TenHuyen,IdTinh")] Huyen huyen)
        {
            if (id != huyen.IdHuyen)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(huyen);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HuyenExists(huyen.IdHuyen))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdTinh"] = new SelectList(_context.Tinhs, "Id", "TenTinh", huyen.IdTinh);
            return View(huyen);
        }

        // GET: Huyen/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Huyens == null)
            {
                return NotFound();
            }

            var huyen = await _context.Huyens
                .Include(h => h.Tinh)
                .FirstOrDefaultAsync(m => m.IdHuyen == id);
            if (huyen == null)
            {
                return NotFound();
            }

            return View(huyen);
        }

        // POST: Huyen/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Huyens == null)
            {
                return Problem("Entity set 'QLThongTinDbContext.Huyens'  is null.");
            }
            var huyen = await _context.Huyens.FindAsync(id);
            if (huyen != null)
            {
                _context.Huyens.Remove(huyen);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HuyenExists(int id)
        {
          return _context.Huyens.Any(e => e.IdHuyen == id);
        }
    }
}

Controllers/TinhController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NguyenThanhQuan_QLThongTin_MVC.Data;
using NguyenThanhQuan_QLThongTin_MVC.Models;

namespace NguyenThanhQuan_QLThongTin_MVC.Controllers
{
    public class TinhController : Controller
    {
        private readonly QLThongTinDbContext _context;

        public TinhController(QLThongTinDbContext context)
        {
            _context = context;
        }
        // GET: Tinh
        public async Task<IActionResult> Index()
        {
              return View(await _context.Tinhs.ToListAsync());
        }

        // GET: Tinh/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Tinhs == null)
            {
                return NotFound();
            }

            var tinh = await _context.Tinhs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tinh == null)
            {
                return NotFound();
            }

            return View(tinh);
        }

        // GET: Tinh/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tinh/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,TenTinh")] Tinh tinh)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tinh);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tinh);
        }

        // GET: Tinh/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Tinhs == null)
            {
                return NotFound();
            }

            var tinh = await _context.Tinhs.FindAsync(id);
            if (tinh == null)
            {
                return NotFound();
            }
            return View(tinh);
        }

        // POST: Tinh/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,TenTinh")] Tinh tinh)
        {
            if (id != tinh.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tinh);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TinhExists(tinh.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tinh);
        }

        // GET: Tinh/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Tinhs == null)
            {
                return NotFound();
            }

            var tinh = await _context.Tinhs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tinh == null)
            {
                return NotFound();
            }

            return View(tinh);
        }

        // POST: Tinh/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Tinhs == null)
            {
                return Problem("Entity set 'QLThongTinDbContext.Tinhs'  is null.");
            }
            var tinh = await _context.Tinhs.FindAsync(id);
            if (tinh != null)
            {
                _context.Tinhs.Remove(tinh);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TinhExists(int id)
        {
          return _context.Tinhs.Any(e => e.Id == id);
        }
    }
}

Views/Tinh/Create.cshtml
@model NguyenThanhQuan_QLThongTin_MVC.Models.Tinh

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Tinh</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TenTinh" class="control-label"></label>
                <input asp-for="TenTinh" class="form-control" />
                <span asp-validation-for="TenTinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Tinh/Delete.cshtml
@model NguyenThanhQuan_QLThongTin_MVC.Models.Tinh

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tinh</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TenTinh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TenTinh)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Tinh/Details.cshtml
@model NguyenThanhQuan_QLThongTin_MVC.Models.Tinh

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Tinh</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TenTinh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TenTinh)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Tinh/Edit.cshtml
@model NguyenThanhQuan_QLThongTin_MVC.Models.Tinh

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Tinh</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="TenTinh" class="control-label"></label>
                <input asp-for="TenTinh" class="form-control" />
                <span asp-validation-for="TenTinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Tinh/Index.cshtml
@model IEnumerable<NguyenThanhQuan_QLThongTin_MVC.Models.Tinh>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TenTinh)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                        <a asp-action="Index" asp-controller="Huyen" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.TenTinh)</a> 
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>